#!/bin/bash
set -e
echo "=============================================="
echo "  Applying Security Hardening Parameters"
echo "=============================================="
echo "Adding kernel parameters via grubby..."
sudo grubby --update-kernel=ALL --args="intel_iommu=on iommu.passthrough=0 iommu.strict=1 mem_sleep_default=s2idle lockdown=confidentiality"
echo ""
echo "Kernel parameters added successfully."
echo ""
echo "=============================================="
echo "  IMPORTANT: Manual Steps Required"
echo "=============================================="
echo ""
echo "1. Ensure Secure Boot is enabled in your BIOS/UEFI."
echo "2. After reboot, verify Secure Boot with:"
echo "   mokutil --sb-state"
echo "3. If Secure Boot shows 'disabled' despite BIOS setting, run:"
echo "   sudo mokutil --enable-validation"
echo "   Then reboot and follow the blue MokManager screen."
echo ""
echo "Reboot now to apply kernel parameter changes."
echo "After reboot, run ./diagnostic.sh to verify hardening."
